### ISSUE TITLE
sprout-osx-apps::flycut doesn't exist

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/sprout-capi#1]
I don't think this recipe exists anymore: https://github.com/cloudfoundry-incubator/sprout-capi/blob/b455f88f9c19bfcf41c3a76a8c369667448b64b4/soloistrc#L12 

See: https://github.com/pivotal-sprout/sprout-osx-apps/tree/master/recipes

**Comment by wendorf** [comment]
Hi @gerg,

Thanks for the heads-up. I had put it back in because I had misread an upstream merge, not noticing we had switched to installing it from homebrew cask anyway.
